<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJaCPePx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJaCPePx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJaCPePx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJaCPePx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJaCPePx\App_KernelDevDebugContainer([
    'container.build_hash' => 'JaCPePx',
    'container.build_id' => '68bfb4bc',
    'container.build_time' => 1760425245,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJaCPePx');
